baseURL = 'https://swampbear.github.io/jobjorn.no/'
languageCode = 'en-us'
title = 'Jobjorn Rokenes Myren'

[params]
  author = 'Jobjorn Rokenes Myren'
  description = 'Personal homepage'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
